name: Deploy Pre-Built Dist via SSH

on:
  push:
    branches:
      - main
      - qa
      - demo

jobs:
  deploy:
    runs-on: self-hosted

    # DITO ILALAGAY ANG ENVIRONMENT VARIABLES PARA HINDI MAG-FAIL ANG NODE 24 SA WINDOWS 7/8
    env:
      NODE_SKIP_PLATFORM_CHECK: '1'
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Target Directory
        id: set-dir
        shell: bash
        run: |
          case "${{ github.ref_name }}" in
            "demo") echo "target=/volume1/EKSYSTEM/EKSystem Version 3.5/GH/demo" >> $GITHUB_OUTPUT ;;
            "qa") echo "target=/volume1/EKSYSTEM/EKSystem Version 3.5/GH/qa" >> $GITHUB_OUTPUT ;;
            "main") echo "target=/volume1/EKSYSTEM/EKSystem Version 3.5/GH" >> $GITHUB_OUTPUT ;;
          esac

      - name: Copy Files via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEV_HOST_KEY }}
          username: ${{ secrets.DEV_USER_KEY }}
          password: ${{ secrets.DEV_PASSWORD_KEY }}
          source: "./*"
          target: ${{ steps.set-dir.outputs.target }}
          rm: true
          strip_components: 0